### ISSUE TITLE
With csv-parse 5.01 release the module does not work anymore

### ISSUE THREAD

**Issue by Villaquiranm** [ankane/secure-spreadsheet#11]
With the new release of 'csv-parse' the module stopped working with the error:
When trying to execute cli.js directly from the repository

```
(node:5984) ExperimentalWarning: The ESM module loader is experimental.
file:///C:/Dev/secure-spreadsheet/src/cli.js:5
import parse from 'csv-parse';
       ^^^^^
SyntaxError: The requested module 'csv-parse' does not provide an export named 'default'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:136:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```

When using the installed module:

``` 
root@6929069cb676:/src/pkg/cryptography/encrypter# echo "var,value\ntemp,10\n" | secure-spreadsheet --password secret > output.xlsx
Error: parse is not a function
```

This is because 16 hours before csv-parse published a mayor upgrade 5.0.1. That is not compatible anymore.

I propose to fix the dependencies version with `^` in order to prevent the module to update a mayor and possible not compatible version of the dependancies.

**Comment by ankane** [comment]
Hey @Villaquiranm, thanks for reporting and investigating! Just added support for csv-parse 5.

**Comment by Villaquiranm** [comment]
No problem thank you for the module :)
