### ISSUE TITLE
secure-spreadsheet does not working via python3.10 subprocess module

### ISSUE THREAD

**Issue by hyeonsoo-kim** [ankane/secure-spreadsheet#14]
I was run below script ( save xlsx bytes to BytesIO and use it for input )

```python
import pandas as pd
from subprocess import check_output
from io import BytesIO
df = pd.read_csv("SalesJan2009.csv")

bio = BytesIO()

with pd.ExcelWriter(bio,'openpyxl') as xlw:
    df.to_excel(xlw, sheet_name="yallacha")

print(check_output(args=['secure-spreadsheet','--password','sectet','--input-format','xlsx'],input=bio.getvalue()))
``` 

and I have got error below. and got exception "subprocess.CalledProcessError"

![image](https://github.com/ankane/secure-spreadsheet/assets/18733991/225cf476-66c9-4b9d-9800-b6ebc9985d44)

+) When I change pd.ExcelWriter's engine to xlsxwiter, secure-spreadsheet works correctly. but when engine of pd.ExcelWriter id "openpyxl",  secure-spreadsheet does not works

**Comment by ankane** [comment]
Hi @hyeonsoo-kim, thanks for reporting. Looks like it's due to https://github.com/dtjohnson/xlsx-populate/issues/164, so would need to be addressed there.
