### ISSUE TITLE
`Error: program.option is not a function` due to depending commander.js v12.0.0 release

### ISSUE THREAD

**Issue by HosakaKeigo** [ankane/secure-spreadsheet#15]
# Problem
First of all, thank you for the library.

I was using `secure-spreadsheet` for xlsx encryption with Python. 
Everything worked fine until I came across `Error: program.option is not a function` in this February.

# Info
After a research I found commander.js, which is [one of the dependencies of secure-spreadsheet](https://github.com/ankane/secure-spreadsheet/blob/4924b867127c3fb727ec8b895c89128e298949f8/package.json#L15-L16), has been updated to v12 on February 3rd.
- https://github.com/tj/commander.js

This update introduces several breaking changes including

> - Breaking: Commander 12 requires Node.js v18 or higher
> - Breaking: removed default export of a global Command instance from CommonJS
https://github.com/tj/commander.js/releases/tag/v12.0.0

Since `secure-spreadsheet` currently install commander v.12, this library is also affected by this.

```json
    "commander": ">=7",
```

Now in `src/cli.js` there is default import of `program`.

```js
const program = require('commander');

[...]

program
  .option('--password <password>', 'Password')
  .option('--input-format <format>', 'Input format')
  .parse(process.argv);

```
https://github.com/ankane/secure-spreadsheet/blob/4924b867127c3fb727ec8b895c89128e298949f8/src/cli.js#L5

# Suggestion
One solution is to specify commander.js version, namely

```diff
- "commander": ">=7",
+ "commander": ">=7.0.0 <12.0.0",
```

It's relatively safe, but obvious drawback is this library is pegged to under v12.

Another is to rewrite default import as stated in commander.js docs.
https://github.com/tj/commander.js/blob/master/docs/deprecated.md#default-import-of-global-command-object

```diff
- const program = require('commander');
+ const { program } = require('commander');
```

I tried the second fix on my local and tested as private package, and it seems to work as before.
But I am not sure about backward compatibilities.

I appreciate if @ankane confirm this problem and solution.

# Sample Code
Lastly here's sample code in question.
```py
def encrypt_file(input_file_path, output_file_path, password):
    cat_process = subprocess.Popen(["cat", input_file_path], stdout=subprocess.PIPE)

    secure_spreadsheet_process = subprocess.Popen(
        ["secure-spreadsheet", "--password", password, "--input-format", "xlsx"],
        stdin=cat_process.stdout,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE
    )

    with open(output_file_path, "wb") as f:
        while True:
            data = secure_spreadsheet_process.stdout.read(1024)
            if not data:
                break
            f.write(data)

    cat_process.wait()
    secure_spreadsheet_process.wait()
    stdout, stderr = secure_spreadsheet_process.communicate()
    if stderr:
        print("Error:", stderr.decode()) # Error: program.option is not a function
```

**Comment by ankane** [comment]
Hi @HosakaKeigo, thanks for the detailed report! It looks like the named export works in Commander.js 7+, so think that's the better option. Will push a new release shortly.

**Comment by HosakaKeigo** [comment]
@ankane 
Ah, thanks for prompt response!

I've just made PR for this issue. (Though lacking testing)
Hope this helps you.
- https://github.com/ankane/secure-spreadsheet/pull/16

Edit: Closed PR because of 5c7696dc5e2e923e945a8c040756658359e879e7

**Comment by ankane** [comment]
It looks like NPM still downloads the latest version of Commander.js even when it's not compatible with the version of Node.js, so needed to limit the version as well.

Just pushed 0.2.1. Thanks again!

**Comment by HosakaKeigo** [comment]
@ankane

Thank you for update!

After having reinstalled I confirmed my Python code works as expected with Node.js v20.11.0.
