### ISSUE TITLE
how to generate XLSX file in the browser

### ISSUE THREAD

**Issue by MaeCess** [ankane/secure-spreadsheet#2]
Hi i tried the the ruby code in the documentation. the "output.xlsx" file created to my project file. is this possible to trigger on the browser? for example the user click the button and then the "output.xlsx(with password)" file will downloaded?

**Comment by ankane** [comment]
Hey @MaeCess, the last line in the example is what saves the encrypted data to a file, so you can replace it with code to pass `result` in an HTTP response instead.

**Comment by MaeCess** [comment]
@ankane i will search how to do that. and thanks for the idea.
