### ISSUE TITLE
Extend to allow no password option

### ISSUE THREAD

**Issue by jamespavett** [ankane/secure-spreadsheet#3]
Hello,

Not sure if it would be out of scope for this project, but would you be able to change it so that the CLI commands allows you to just convert CSV to XLSX without a password.

I know this is a secure spreadsheet package, however I would have expected if the --password option was left out, it would have just directly converted the document. However it generates a 0kb XLSX file.

**Comment by ankane** [comment]
Hey @jamespavett, thanks for the suggestion. You should get a `--password required` error when leaving out the password. As you mentioned, I think unencrypted CSV to XLSX conversion is outside the scope of the project.

**Comment by jamespavett** [comment]
Makes sense! Just thought I would ask the question. 

Thank you for this package btw, you saved me because the encryption functionality in PHPSpreadsheet doesn't work currently.
