### ISSUE TITLE
XLSM support 

### ISSUE THREAD

**Issue by bplus** [ankane/secure-spreadsheet#6]
Hello, 

Would you be able to add XLSM support to this project? I forked your code a few weeks ago to add it, and it has been working fine.  There are no additional changes needed other than checking for 'xlsm' in addition to 'xlsx' in this line of src/cli.js:

`if (options.inputFormat == "xlsx") {`

**Comment by bplus** [comment]
You can see my example here, but I figured you'd probably want to do it more succinctly than an additional if/else. 

https://github.com/bplus/secure-spreadsheet/blob/master/src/cli.js

**Comment by ankane** [comment]
Hey @bplus, thanks for sharing. I don't think XLSM files are common enough to officially support, but good to know it's fairly straightforward to do if needed.
