### ISSUE TITLE
using secure-spreadsheet in PHP script not work correctly

### ISSUE THREAD

**Issue by wijdanMT** [ankane/secure-spreadsheet#8]
Hi,
I am trying to use secure-spreadsheet with my PHP scripts to encrypt an excel sheet,
when using the secure-spreadsheet as a command in cmd it works correctly,
`secure-spreadsheet --password password < C:\wamp64\www\test.csv > C:\wamp64\www\test.xlsx`

but when using PHP script it generates the file, but it can't open as the following image:
![image](https://user-images.githubusercontent.com/80570482/111064681-11125980-84be-11eb-9512-80cb2687fa37.png)

**this the PHP script:**
`$infilepath = 'C:\wamp64\www\test.csv';
$outfilepath = 'C:\wamp64\www\test.xlsx';
$encryptionPassword = 'password';
//$encryptCommand = "type $infilepath | secure-spreadsheet --password $encryptionPassword > $outfilepath";
$encryptCommand = "secure-spreadsheet --password $encryptionPassword < $infilepath > $outfilepath";
exec($encryptCommand);
//system($encryptCommand);
`

**I will be appreciated for any guides to work around this issue.**

**Comment by ankane** [comment]
Hey @wijdanMT, which versions of secure-spreadsheet are you on? Also, is the output file empty or does it have some data? On Mac, I was able to get it to work with `exec`, but you could also use something like `proc_open` (similar to the Ruby example).

**Comment by ankane** [comment]
I haven't worked with PHP in a while, but the `proc_open` version could look something like this:

```php
<?php

$csv_str = "this,is,a,test";

$descriptorspec = array(
  0 => array("pipe", "r"),
  1 => array("pipe", "w")
);

$process = proc_open("secure-spreadsheet --password secret", $descriptorspec, $pipes);

if (is_resource($process)) {
    fwrite($pipes[0], $csv_str);
    fclose($pipes[0]);

    $result = stream_get_contents($pipes[1]);
    fclose($pipes[1]);

    $return_value = proc_close($process);
    if ($return_value != 0) {
      die("Command failed");
    }
}

$file = fopen("output.xlsx", "w") or die("Unable to open file!");
fwrite($file, $result);
fclose($file);
```

**Comment by wijdanMT** [comment]
Sorry to respond lately, Actually I am using version '0.1.3' of the secure-spreadsheet.
Thank you for your time, your code worked for me.
